### ISSUE TITLE
[Objective-C] Como fazer o comparativo de um inteiro com um elemento de um NSMutableArray?

### ISSUE THREAD

**Issue by Viniciuscarvalho** [CocoaHeadsBrasil/forum#6]
# Qual o problema ou dúvida?

Tenho a seguinte chamada da minha API que me retorna os 10 resultados e o meu `
userId`, só que o problema é que quando o meu `userId` ele é duplicando aparecendo também na última posição, tentei fazer assim `[ranking removeLastObject];`, mas acabou não tendo o resultado que esperava.
# O que você já tentou para resolver?

Tentei criar um comparativo para verificar se o `userId`está contido no `ranking`, mas não consegui ter esse comparativo com o `===` se ele está entre os 10 usuários.
# Snippet

``` swift
[Util loadRankingFromType:nil orFromUser:[Util getCurrentUser].userId onSuccess:^(NSMutableArray *ranking) {

        self.general = ranking;
        [self didFinishRequest];

    } onFailure:^(NSError *error)
```
# Detalhes sobre seu ambiente

**Comment by brurend** [comment]
Faltou algo no texto: só que o problema é que quando o meu `userId` ele é duplicando.

Não teria alguma palavra entre o `userId` e "ele"?

**Comment by DougFischer** [comment]
Já tentou usar o containsObject do NSMutableArray para verificar se seu userId está contido no array ranking? 

Verifique também se seu objeto é um NSString. Se for, você deve usar o isEqualToString.

**Comment by Viniciuscarvalho** [comment]
@brurend O problema não é quando ele é duplicado, o problema é que quando o `userId` está entre os 10 primeiros do `ranking` ele aparece duplicado, com a posição e também na última posição do Array, entendeu?

@DougFischer usei esse containsObject já, vou tentar agora o isEqualToString, pra verificar se ele está entre os 10 e remover quando ele estiver.

**Comment by Viniciuscarvalho** [comment]
Pessoal consegui resolver, era uma interação para verificar se o meu `userId` estava contido no ranking.
